cluster_name: "prod-kind"
kubernetes_version: "v1.28.0"
worker_nodes: 1  # 1 control plane + 1 worker = 2 nodes total
nodes: 1
# Memory configuration for better resource management
node_memory: "2Gi"
total_memory_limit: "4Gi"
port_mappings:
  - containerPort: 30000
    hostPort: 30010
    protocol: "TCP"
  - containerPort: 30001
    hostPort: 30011
    protocol: "TCP"
wait_for_ready: true
wait_for_ready_timeout: "300s"
