namespace: "grafana"
chart_version: "7.0.0"
admin_password: "admin123"
persistence:
  enabled: true
  size: "10Gi"
service:
  type: "NodePort"
  port: 80
  nodePort: 30000
values:
  grafana:
    adminPassword: "admin123"
    persistence:
      enabled: true
      size: "10Gi"
    service:
      type: "NodePort"
      port: 80
      nodePort: 30000
